fix paths to old repositories now that I've moved away from groups

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
 # Run this:
-# bash < <(curl -s https://gitlab.com/tspub/bin/raw/master/bootstrap)
+# bash < <(curl -s https://gitlab.com/tslight/bin/raw/master/bootstrap)
 
 DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-URL="git@gitlab.com:tspub"
+URL="git@gitlab.com:tslight"
 
 update_env() {
     export PATH="$PATH:$HOME/bin:$HOME/.local/bin"
@@ -18,44 +18,44 @@ clone_repo() {
     local url="$URL/${name}.git"
 
     if [ -d "$dest/.git" ]; then
-	echo "$url already cloned to $dest."
+        echo "$url already cloned to $dest."
     else
-	if mkdir -p "$dest"; then
-	    if git clone -q "$url" "$dest"; then
-		echo "Successfully cloned $url."
-	    else
-		echo "Failed to clone $url."
-		exit 1
-	    fi
-	else
-	    echo "Could not create $dest."
-	    exit 1
-	fi
+        if mkdir -p "$dest"; then
+            if git clone -q "$url" "$dest"; then
+                echo "Successfully cloned $url."
+            else
+                echo "Failed to clone $url."
+                exit 1
+            fi
+        else
+            echo "Could not create $dest."
+            exit 1
+        fi
     fi
 }
 
 lazypkg() {
     case "$OSTYPE" in
-	darwin*)
-	    lazymac
-	    ;;
-	linux*)
-	    source /etc/os-release
-	    case "$ID" in
-		debian|ubuntu)
-		    "$HOME/bin/lazydeb"
-		    ;;
-		centos|fedora)
-		    "$HOME/bin/lazyrpm"
-		    ;;
-		*)
-		    echo "$ID not supported"
-		    ;;
-	    esac
-	    ;;
-	*)
-	    "$OSTYPE not supported"
-	    ;;
+        darwin*)
+            lazymac
+            ;;
+        linux*)
+            source /etc/os-release
+            case "$ID" in
+                debian|ubuntu)
+                    "$HOME/bin/lazydeb"
+                    ;;
+                centos|fedora)
+                    "$HOME/bin/lazyrpm"
+                    ;;
+                *)
+                    echo "$ID not supported"
+                    ;;
+            esac
+            ;;
+        *)
+            "$OSTYPE not supported"
+            ;;
     esac
 }
 
@@ -63,17 +63,17 @@ getlazy() {
     local token="$1" dest="$2"
 
     { [ -d /tmp/lazygit ] || git clone "$URL/js/lazygit" /tmp/lazygit; } && \
-	cd /tmp/lazygit && \
-	npm install && \
-	node ./lazygitlab.js "$token" "$dest" && \
-	cd "$dest/tspub/js/lazygit" &&
-	npm install && npm link
+        cd /tmp/lazygit && \
+        npm install && \
+        node ./lazygitlab.js "$token" "$dest" && \
+        cd "$dest/gitlab/tslight/lazygit.js" &&
+        npm install && npm link
 }
 
 cleanup() {
     # Use "${var:?}" to ensure this never expands to /bin
     rm -rf "${var:?HOME}/bin" &&
-	ln -sf "${HOME}/src/tspub/bin" "${HOME}/bin"
+        ln -sf "${HOME}/src/gitlab/tslight/bin" "${HOME}/bin"
 }
 
 main() {
